import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database, Enums, Json, Tables } from './database.types';

export type PublicAppConfigEntry={key:string;value_json:Json;value_type:string;updated_at:string};
export type OnboardingStatus={user_id:string;age_verified:boolean;policies_accepted:boolean;creator_terms_accepted:boolean;account_status:string;profile_status:string};
export type CompleteOnboardingInput={dateOfBirth:string;termsVersion:string;communityRulesVersion:string;ageVerificationMethod?:string};
export type UpdateProfileInput={username:string;displayName:string;bio?:string|null;gender?:Enums<'gender_identity'>;provinceId?:number|null;discoveryEnabled?:boolean;nearbyEnabled?:boolean};
function firstOrThrow<T>(rows:T[]|null,operation:string):T{const row=rows?.[0];if(!row)throw new Error(`${operation} returned no row.`);return row;}
export async function getPublicAppConfig(client:SupabaseClient<Database>):Promise<PublicAppConfigEntry[]>{const{data,error}=await client.rpc('get_public_app_config');if(error)throw error;return data??[];}
export async function getMyOnboardingStatus(client:SupabaseClient<Database>):Promise<OnboardingStatus>{const{data,error}=await client.rpc('get_my_onboarding_status');if(error)throw error;return firstOrThrow(data,'get_my_onboarding_status');}
export async function completeMyOnboarding(client:SupabaseClient<Database>,input:CompleteOnboardingInput){const{data,error}=await client.rpc('complete_my_onboarding',{p_date_of_birth:input.dateOfBirth,p_terms_version:input.termsVersion,p_community_rules_version:input.communityRulesVersion,...(input.ageVerificationMethod?{p_age_verification_method:input.ageVerificationMethod}:{})});if(error)throw error;return firstOrThrow(data,'complete_my_onboarding');}
export async function updateMyProfile(client:SupabaseClient<Database>,input:UpdateProfileInput):Promise<Tables<'profiles'>>{const{data,error}=await client.rpc('update_my_profile',{p_username:input.username,p_display_name:input.displayName,...(input.bio==null?{}:{p_bio:input.bio}),...(input.gender?{p_gender:input.gender}:{}),...(input.provinceId==null?{}:{p_province_id:input.provinceId}),...(input.discoveryEnabled==null?{}:{p_discovery_enabled:input.discoveryEnabled}),...(input.nearbyEnabled==null?{}:{p_nearby_enabled:input.nearbyEnabled})});if(error)throw error;return data;}
export async function applyForCreator(client:SupabaseClient<Database>,creatorBio:string):Promise<'pending'>{const{data:userData,error:userError}=await client.auth.getUser();if(userError)throw userError;const user=userData.user;if(!user)throw new Error('Authentication required.');const{data,error}=await client.from('creator_profiles').insert({user_id:user.id,creator_bio:creatorBio}).select('creator_status').single();if(error)throw error;if(data.creator_status!=='pending')throw new Error('Unexpected Creator application status.');return 'pending';}
