import { describe, expect, it } from 'vitest';
import { accessibility,chonButtons,chonColors,colors,contrastRatio,luxyBrand,luxyBreakpoints,luxyColors,luxyLayout,luxyRadii,luxySpacing,meetsWcagAa,resolveLuxyResponsiveShellMode,resolveLuxyShellMode } from './index';
describe('Chon.Love shared UI foundation',()=>{
  it('keeps minimum touch targets at least 44 CSS points',()=>{expect(accessibility.minimumTouchTarget).toBeGreaterThanOrEqual(44);expect(accessibility.preferredTouchTarget).toBeGreaterThanOrEqual(accessibility.minimumTouchTarget)});
  it('uses the Chon.Love authenticated navigation hierarchy',()=>{expect(luxyBrand.productName).toBe('Chon.Love');expect(luxyBrand.primaryNavigation).toEqual(['Kết nối','Yêu thích','Tin nhắn','Nâng cấp'])});
  it('uses the Seeking-derived ink and coral palette instead of the historical MyFan pink',()=>{expect(luxyColors.ink).toBe('#081726');expect(luxyColors.brandCoral).toBe('#FF4A4A');expect(colors.primary).toBe(luxyColors.ink);expect(Object.values(luxyColors)).not.toContain('#D81B60')});
  it('locks chrome gold as the Chon.Love semantic gold for future UI',()=>{expect(chonColors.gold).toBe('#FFCD46');expect(chonColors.goldChrome).toBe('#FFCD46');expect(chonButtons.goldFilled.background).toBe('#FFCD46');expect(chonButtons.goldFilled.hoverBackground).toBe('#FFCD46');expect(chonButtons.goldFilled.border).toBe('#FFCD46')});
  it('locks the core responsive and Search layout measurements',()=>{expect(luxyBreakpoints.compactPhone).toBe(430);expect(luxyBreakpoints.mobile).toBe(768);expect(luxyBreakpoints.desktop).toBe(1024);expect(luxyLayout.authenticatedPhoneTopHeight).toBeGreaterThanOrEqual(44);expect(luxyLayout.authenticatedPhoneNavHeight).toBeGreaterThanOrEqual(44);expect(luxyLayout.searchSidebarWidth).toBeGreaterThanOrEqual(330);expect(luxyLayout.searchSidebarWidth).toBeLessThanOrEqual(370);expect(luxyLayout.memberCardAspectRatio).toBeCloseTo(.75,4);expect(luxyRadii.pill).toBe(999);expect(luxySpacing.huge).toBe(64)});
  it('starts the full desktop shell at 1024px exactly',()=>{expect(resolveLuxyShellMode(390)).toBe('compact');expect(resolveLuxyShellMode(768)).toBe('compact');expect(resolveLuxyShellMode(1023)).toBe('compact');expect(resolveLuxyShellMode(1024)).toBe('desktop');expect(resolveLuxyShellMode(1440)).toBe('desktop')});
  it('splits phone, tablet and desktop responsive shell modes at 768/1024px',()=>{expect(resolveLuxyResponsiveShellMode(390)).toBe('phone');expect(resolveLuxyResponsiveShellMode(430)).toBe('phone');expect(resolveLuxyResponsiveShellMode(767)).toBe('phone');expect(resolveLuxyResponsiveShellMode(768)).toBe('tablet');expect(resolveLuxyResponsiveShellMode(1023)).toBe('tablet');expect(resolveLuxyResponsiveShellMode(1024)).toBe('desktop');expect(resolveLuxyResponsiveShellMode(1440)).toBe('desktop')});
  it.each([[colors.text,colors.surface],[colors.muted,colors.surface],[colors.surface,colors.primary],[colors.surface,colors.danger]])('meets WCAG AA contrast for %s on %s',(foreground,background)=>{expect(meetsWcagAa(foreground,background)).toBe(true)});
  it('calculates the black-on-white ratio',()=>{expect(contrastRatio('#000000','#FFFFFF')).toBeCloseTo(21,4)});
});
