-- MyFan Phase B / Session 6: core profiles, private identity, Creator roles and config.
create extension if not exists citext with schema extensions;
create extension if not exists postgis with schema extensions;
create extension if not exists pg_trgm with schema extensions;
create extension if not exists pgtap with schema extensions;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to service_role;

create type public.profile_status as enum ('incomplete','pending_review','active','suspended','deactivated','deleted');
create type public.gender_identity as enum ('female','male','non_binary','other','prefer_not_to_say');
create type public.creator_status as enum ('not_applied','pending','approved','rejected','suspended','closed');
create type private.age_verification_method as enum ('self_declared','document','manual_review','third_party');
create type private.account_status as enum ('active','suspended','deactivated','deletion_requested','deleted');
create type private.user_role as enum ('user','creator','moderator','finance_admin','super_admin');
create type private.config_value_type as enum ('integer','boolean','string','json');

create table public.administrative_areas (
  id bigint generated by default as identity primary key,
  code text not null,
  name_vi text not null,
  name_en text,
  area_type text not null,
  parent_id bigint references public.administrative_areas(id) on delete restrict,
  country_code char(2) not null default 'VN',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint administrative_areas_code_format check (code ~ '^[A-Z0-9_-]{1,32}$'),
  constraint administrative_areas_name_vi_length check (char_length(name_vi) between 1 and 120),
  constraint administrative_areas_name_en_length check (name_en is null or char_length(name_en) between 1 and 120),
  constraint administrative_areas_type_format check (area_type ~ '^[a-z][a-z0-9_]{1,31}$'),
  constraint administrative_areas_country_code_format check (country_code ~ '^[A-Z]{2}$'),
  constraint administrative_areas_not_self_parent check (parent_id is null or parent_id <> id),
  unique (country_code, code)
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username extensions.citext unique,
  display_name text,
  bio text,
  gender public.gender_identity not null default 'prefer_not_to_say',
  province_id bigint references public.administrative_areas(id) on delete set null,
  avatar_media_id uuid,
  profile_status public.profile_status not null default 'incomplete',
  discovery_enabled boolean not null default false,
  nearby_enabled boolean not null default false,
  is_creator boolean not null default false,
  last_active_at timestamptz,
  username_changed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint profiles_username_length check (username is null or char_length(username::text) between 3 and 30),
  constraint profiles_username_format check (username is null or username::text ~ '^[A-Za-z0-9][A-Za-z0-9_]{2,29}$'),
  constraint profiles_username_reserved check (username is null or lower(username::text) not in ('admin','administrator','api','auth','billing','creator_support','finance','help','moderator','myfan','official','root','security','service','staff','support','system','webmaster')),
  constraint profiles_display_name_length check (display_name is null or char_length(btrim(display_name)) between 1 and 80),
  constraint profiles_bio_length check (bio is null or char_length(bio) <= 500),
  constraint profiles_nearby_requires_discovery check (not nearby_enabled or discovery_enabled),
  constraint profiles_deleted_state check ((deleted_at is null and profile_status <> 'deleted') or (deleted_at is not null and profile_status = 'deleted'))
);

create table private.user_identity (
  user_id uuid primary key references auth.users(id) on delete cascade,
  date_of_birth date,
  age_verified_at timestamptz,
  age_verification_method private.age_verification_method,
  terms_version text,
  terms_accepted_at timestamptz,
  community_rules_version text,
  community_rules_accepted_at timestamptz,
  creator_terms_version text,
  creator_terms_accepted_at timestamptz,
  account_status private.account_status not null default 'active',
  suspension_reason_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_identity_age_verification_pair check ((age_verified_at is null and age_verification_method is null) or (age_verified_at is not null and age_verification_method is not null and date_of_birth is not null)),
  constraint user_identity_verified_adult check (age_verified_at is null or date_of_birth <= ((age_verified_at at time zone 'UTC')::date - interval '18 years')::date),
  constraint user_identity_terms_pair check ((terms_version is null and terms_accepted_at is null) or (terms_version is not null and terms_accepted_at is not null)),
  constraint user_identity_rules_pair check ((community_rules_version is null and community_rules_accepted_at is null) or (community_rules_version is not null and community_rules_accepted_at is not null)),
  constraint user_identity_creator_terms_pair check ((creator_terms_version is null and creator_terms_accepted_at is null) or (creator_terms_version is not null and creator_terms_accepted_at is not null)),
  constraint user_identity_suspension_reason check (account_status = 'suspended' or suspension_reason_code is null)
);

create table public.creator_profiles (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  creator_status public.creator_status not null default 'pending',
  creator_bio text,
  fan_threshold_units bigint not null default 1000,
  payout_eligible boolean not null default false,
  joined_at timestamptz not null default now(),
  approved_at timestamptz,
  suspended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint creator_profiles_bio_length check (creator_bio is null or char_length(creator_bio) <= 1000),
  constraint creator_profiles_fan_threshold_nonnegative check (fan_threshold_units >= 0),
  constraint creator_profiles_approval_state check (approved_at is null or creator_status in ('approved','suspended','closed')),
  constraint creator_profiles_suspension_state check (suspended_at is null or creator_status in ('suspended','closed')),
  constraint creator_profiles_payout_state check (payout_eligible = false or creator_status = 'approved')
);

create table private.user_roles (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  role private.user_role not null,
  granted_by uuid references auth.users(id) on delete set null,
  granted_at timestamptz not null default now(),
  revoked_at timestamptz,
  constraint user_roles_revocation_time check (revoked_at is null or revoked_at >= granted_at)
);
create unique index user_roles_one_active_role_idx on private.user_roles(user_id, role) where revoked_at is null;

create table private.app_config (
  key text primary key,
  value_json jsonb not null,
  value_type private.config_value_type not null,
  description text not null,
  is_public boolean not null default false,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_config_key_format check (key ~ '^[a-z][a-z0-9_]{2,63}$'),
  constraint app_config_description_length check (char_length(description) between 1 and 500),
  constraint app_config_value_type_matches check ((value_type='integer' and jsonb_typeof(value_json)='number' and (value_json #>> '{}') ~ '^-?[0-9]+$') or (value_type='boolean' and jsonb_typeof(value_json)='boolean') or (value_type='string' and jsonb_typeof(value_json)='string') or value_type='json')
);

create index administrative_areas_parent_idx on public.administrative_areas(parent_id);
create index administrative_areas_active_country_sort_idx on public.administrative_areas(country_code,is_active,sort_order,id);
create index administrative_areas_name_vi_trgm_idx on public.administrative_areas using gin (name_vi extensions.gin_trgm_ops);
create index profiles_province_active_idx on public.profiles(province_id,profile_status,discovery_enabled) where deleted_at is null;
create index profiles_status_created_idx on public.profiles(profile_status,created_at desc) where deleted_at is null;
create index profiles_creator_active_idx on public.profiles(is_creator,profile_status,created_at desc) where deleted_at is null;
create index profiles_last_active_idx on public.profiles(last_active_at desc) where deleted_at is null;
create index creator_profiles_status_created_idx on public.creator_profiles(creator_status,created_at desc);
create index user_roles_user_active_idx on private.user_roles(user_id,role) where revoked_at is null;
create index app_config_public_idx on private.app_config(is_public,key) where is_public;

create or replace function private.set_updated_at() returns trigger language plpgsql set search_path='' as $$begin new.updated_at=now(); return new; end;$$;
create trigger administrative_areas_set_updated_at before update on public.administrative_areas for each row execute function private.set_updated_at();
create trigger profiles_set_updated_at before update on public.profiles for each row execute function private.set_updated_at();
create trigger user_identity_set_updated_at before update on private.user_identity for each row execute function private.set_updated_at();
create trigger creator_profiles_set_updated_at before update on public.creator_profiles for each row execute function private.set_updated_at();
create trigger app_config_set_updated_at before update on private.app_config for each row execute function private.set_updated_at();

create or replace function private.validate_user_identity() returns trigger language plpgsql set search_path='' as $$begin if new.date_of_birth is not null and new.date_of_birth>current_date then raise exception using errcode='22008',message='date_of_birth cannot be in the future'; end if; return new; end;$$;
create trigger user_identity_validate before insert or update on private.user_identity for each row execute function private.validate_user_identity();

create or replace function private.handle_new_auth_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id) values(new.id) on conflict(id) do nothing; insert into private.user_identity(user_id) values(new.id) on conflict(user_id) do nothing; insert into private.user_roles(user_id,role) values(new.id,'user'::private.user_role) on conflict do nothing; return new; end;$$;
revoke all on function private.handle_new_auth_user() from public,anon,authenticated;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function private.handle_new_auth_user();
insert into public.profiles(id) select id from auth.users on conflict(id) do nothing;
insert into private.user_identity(user_id) select id from auth.users on conflict(user_id) do nothing;
insert into private.user_roles(user_id,role) select id,'user'::private.user_role from auth.users on conflict do nothing;

create or replace function private.sync_profile_creator_flag() returns trigger language plpgsql security definer set search_path='' as $$begin update public.profiles set is_creator=(new.creator_status='approved'::public.creator_status) where id=new.user_id; return new; end;$$;
revoke all on function private.sync_profile_creator_flag() from public,anon,authenticated;
create trigger creator_profiles_sync_profile_flag after insert or update of creator_status on public.creator_profiles for each row execute function private.sync_profile_creator_flag();

create or replace function public.is_current_user_adult() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from private.user_identity ui where ui.user_id=(select auth.uid()) and ui.age_verified_at is not null and ui.date_of_birth <= (current_date-interval '18 years')::date and ui.terms_accepted_at is not null and ui.community_rules_accepted_at is not null and ui.account_status='active'::private.account_status);$$;
revoke all on function public.is_current_user_adult() from public,anon;
grant execute on function public.is_current_user_adult() to authenticated,service_role;

create or replace function public.complete_my_onboarding(p_date_of_birth date,p_terms_version text,p_community_rules_version text,p_age_verification_method text default 'self_declared') returns table(user_id uuid,age_verified boolean,account_status text,completed_at timestamptz) language plpgsql security definer set search_path='' as $$declare v_user_id uuid:=(select auth.uid()); v_now timestamptz:=now(); v_existing_dob date; v_method private.age_verification_method; begin if v_user_id is null then raise exception using errcode='28000',message='authentication required'; end if; if p_date_of_birth is null or p_date_of_birth>current_date then raise exception using errcode='22008',message='invalid date_of_birth'; end if; if p_date_of_birth>(current_date-interval '18 years')::date then raise exception using errcode='22023',message='user must be at least 18 years old'; end if; if p_age_verification_method not in('self_declared','document','manual_review','third_party') then raise exception using errcode='22023',message='invalid age verification method'; end if; v_method:=p_age_verification_method::private.age_verification_method; select ui.date_of_birth into v_existing_dob from private.user_identity ui where ui.user_id=v_user_id; if v_existing_dob is not null and v_existing_dob<>p_date_of_birth then raise exception using errcode='22023',message='verified date_of_birth cannot be changed by client'; end if; if nullif(btrim(p_terms_version),'') is null or char_length(p_terms_version)>64 then raise exception using errcode='22023',message='invalid terms version'; end if; if nullif(btrim(p_community_rules_version),'') is null or char_length(p_community_rules_version)>64 then raise exception using errcode='22023',message='invalid community rules version'; end if; insert into private.user_identity(user_id,date_of_birth,age_verified_at,age_verification_method,terms_version,terms_accepted_at,community_rules_version,community_rules_accepted_at,account_status) values(v_user_id,p_date_of_birth,v_now,v_method,btrim(p_terms_version),v_now,btrim(p_community_rules_version),v_now,'active'::private.account_status) on conflict on constraint user_identity_pkey do update set date_of_birth=excluded.date_of_birth,age_verified_at=excluded.age_verified_at,age_verification_method=excluded.age_verification_method,terms_version=excluded.terms_version,terms_accepted_at=excluded.terms_accepted_at,community_rules_version=excluded.community_rules_version,community_rules_accepted_at=excluded.community_rules_accepted_at,account_status='active'::private.account_status,suspension_reason_code=null; return query select v_user_id,true,'active'::text,v_now; end;$$;
revoke all on function public.complete_my_onboarding(date,text,text,text) from public,anon;
grant execute on function public.complete_my_onboarding(date,text,text,text) to authenticated,service_role;

create or replace function public.get_my_onboarding_status() returns table(user_id uuid,age_verified boolean,policies_accepted boolean,creator_terms_accepted boolean,account_status text,profile_status text) language sql stable security definer set search_path='' as $$select ui.user_id,(ui.age_verified_at is not null and ui.date_of_birth <= (current_date-interval '18 years')::date),(ui.terms_accepted_at is not null and ui.community_rules_accepted_at is not null),(ui.creator_terms_accepted_at is not null),ui.account_status::text,p.profile_status::text from private.user_identity ui join public.profiles p on p.id=ui.user_id where ui.user_id=(select auth.uid());$$;
revoke all on function public.get_my_onboarding_status() from public,anon;
grant execute on function public.get_my_onboarding_status() to authenticated,service_role;

create or replace function public.update_my_profile(p_username text,p_display_name text,p_bio text default null,p_gender public.gender_identity default 'prefer_not_to_say',p_province_id bigint default null,p_discovery_enabled boolean default true,p_nearby_enabled boolean default false) returns public.profiles language plpgsql security definer set search_path='' as $$declare v_user_id uuid:=(select auth.uid()); v_existing public.profiles%rowtype; v_result public.profiles%rowtype; v_new_username extensions.citext; begin if v_user_id is null then raise exception using errcode='28000',message='authentication required'; end if; if not public.is_current_user_adult() then raise exception using errcode='42501',message='adult onboarding is required'; end if; v_new_username:=nullif(btrim(p_username),'')::extensions.citext; if v_new_username is null then raise exception using errcode='22023',message='username is required'; end if; if nullif(btrim(p_display_name),'') is null then raise exception using errcode='22023',message='display_name is required'; end if; if p_province_id is not null and not exists(select 1 from public.administrative_areas a where a.id=p_province_id and a.is_active) then raise exception using errcode='23503',message='province is not active'; end if; select * into v_existing from public.profiles where id=v_user_id for update; if not found then raise exception using errcode='P0002',message='profile not found'; end if; if v_existing.username is not null and v_existing.username<>v_new_username and v_existing.username_changed_at is not null and v_existing.username_changed_at>now()-interval '30 days' then raise exception using errcode='22023',message='username can be changed once every 30 days'; end if; update public.profiles set username=v_new_username,display_name=btrim(p_display_name),bio=nullif(btrim(p_bio),''),gender=p_gender,province_id=p_province_id,discovery_enabled=p_discovery_enabled,nearby_enabled=p_nearby_enabled,profile_status=case when profile_status in('suspended','deactivated','deleted') then profile_status else 'pending_review'::public.profile_status end,username_changed_at=case when v_existing.username is distinct from v_new_username then now() else v_existing.username_changed_at end where id=v_user_id returning * into v_result; return v_result; end;$$;
revoke all on function public.update_my_profile(text,text,text,public.gender_identity,bigint,boolean,boolean) from public,anon;
grant execute on function public.update_my_profile(text,text,text,public.gender_identity,bigint,boolean,boolean) to authenticated,service_role;

create or replace function public.get_public_app_config() returns table(key text,value_json jsonb,value_type text,updated_at timestamptz) language sql stable security definer set search_path='' as $$select c.key,c.value_json,c.value_type::text,c.updated_at from private.app_config c where c.is_public order by c.key;$$;
revoke all on function public.get_public_app_config() from public;
grant execute on function public.get_public_app_config() to anon,authenticated,service_role;

alter table public.administrative_areas enable row level security;
alter table public.profiles enable row level security;
alter table public.creator_profiles enable row level security;
alter table private.user_identity enable row level security;
alter table private.user_roles enable row level security;
alter table private.app_config enable row level security;
revoke all on table public.administrative_areas,public.profiles,public.creator_profiles from anon,authenticated;
revoke all on table private.user_identity,private.user_roles,private.app_config from public,anon,authenticated;
grant select on table public.administrative_areas,public.profiles,public.creator_profiles to anon,authenticated;
grant all on table public.administrative_areas,public.profiles,public.creator_profiles to service_role;
grant all on table private.user_identity,private.user_roles,private.app_config to service_role;
grant execute on all functions in schema private to service_role;
grant usage,select on all sequences in schema public to service_role;

create policy administrative_areas_read_active on public.administrative_areas for select to anon,authenticated using(is_active);
create policy profiles_read_anon_creators on public.profiles for select to anon using(profile_status='active' and is_creator and deleted_at is null);
create policy profiles_read_authenticated on public.profiles for select to authenticated using(id=(select auth.uid()) or (public.is_current_user_adult() and profile_status='active' and deleted_at is null));
create policy creator_profiles_read_anon_approved on public.creator_profiles for select to anon using(creator_status='approved');
create policy creator_profiles_read_authenticated on public.creator_profiles for select to authenticated using(user_id=(select auth.uid()) or (public.is_current_user_adult() and creator_status='approved'));
grant insert(user_id,creator_bio) on public.creator_profiles to authenticated;
grant update(creator_bio) on public.creator_profiles to authenticated;
create policy creator_profiles_apply_self on public.creator_profiles for insert to authenticated with check(user_id=(select auth.uid()) and public.is_current_user_adult());
create policy creator_profiles_update_own_bio on public.creator_profiles for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));

insert into private.app_config(key,value_json,value_type,description,is_public) values
('heart_units_per_heart','100'::jsonb,'integer','Immutable V1 definition: one heart equals 100 heart units.',true),
('heart_vnd_rate','10000'::jsonb,'integer','Default VND reference rate per heart; transactions snapshot the applied rate.',true),
('creator_share_bps','7000'::jsonb,'integer','Default Creator reward share in basis points.',true),
('platform_share_bps','3000'::jsonb,'integer','Default platform gross share in basis points.',true),
('estimated_google_fee_bps','1500'::jsonb,'integer','Forecast-only Google fee assumption.',false),
('creator_reward_hold_days','14'::jsonb,'integer','Default Creator reward hold period.',true),
('minimum_withdrawal_units','1000'::jsonb,'integer','Minimum Creator reward units for withdrawal.',true),
('maximum_daily_gift_units','{"enabled":false,"units":null,"status":"product_decision_required"}'::jsonb,'json','Daily gift limit pending Product and Risk approval.',false),
('maximum_daily_purchase_units','{"enabled":false,"units":null,"status":"product_decision_required"}'::jsonb,'json','Daily purchase limit pending Product and Risk approval.',false),
('fan_minimum_units','1000'::jsonb,'integer','Default net eligible support threshold for Fan membership.',true),
('location_max_radius_meters','15000'::jsonb,'integer','Maximum nearby radius in meters.',true),
('location_stale_after_days','7'::jsonb,'integer','Stale location threshold in days.',false),
('location_max_accuracy_meters','5000'::jsonb,'integer','Maximum accepted location accuracy in meters.',false),
('account_deletion_grace_days','30'::jsonb,'integer','Account deletion grace period in days.',true)
on conflict(key) do update set value_json=excluded.value_json,value_type=excluded.value_type,description=excluded.description,is_public=excluded.is_public;

alter default privileges in schema private revoke all on tables from public,anon,authenticated;
alter default privileges in schema private revoke all on sequences from public,anon,authenticated;
alter default privileges in schema private revoke all on functions from public,anon,authenticated;
alter default privileges in schema private grant all on tables to service_role;
alter default privileges in schema private grant usage,select on sequences to service_role;
alter default privileges in schema private grant execute on functions to service_role;
comment on schema private is 'Server-only identity, authorization and configuration data; not exposed through the Data API.';
comment on table public.profiles is 'Shared public profile source for Expo Web, Android, iOS, Admin and Public Web; contains no email, DOB, KYC, bank or exact location.';
comment on table private.user_identity is 'Server-only date of birth, age assurance and policy acceptance.';
comment on table private.user_roles is 'Authoritative roles; never derive authorization from raw_user_meta_data.';
comment on table private.app_config is 'Server-owned configuration; clients read public keys only through get_public_app_config().';
