-- MyFan Phase B / Session 7
-- Private exact location, privacy-preserving discovery, social graph and direct messaging.

create type public.friendship_status as enum ('pending','accepted','declined','cancelled');
create type public.report_status as enum ('submitted','triaged','in_review','resolved','dismissed');
create type public.report_priority as enum ('low','normal','high','urgent');
create type public.conversation_type as enum ('direct');
create type public.message_type as enum ('text','gift','system');
create type public.message_moderation_status as enum ('unreviewed','approved','flagged','removed');

create table private.user_locations (
  user_id uuid primary key references auth.users(id) on delete cascade,
  location extensions.geography(Point,4326) not null,
  accuracy_meters integer not null,
  captured_at timestamptz not null,
  consented_at timestamptz not null,
  is_enabled boolean not null default true,
  source text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_locations_accuracy_nonnegative check (accuracy_meters>=0),
  constraint user_locations_accuracy_reasonable check (accuracy_meters<=50000),
  constraint user_locations_captured_not_future check (captured_at<=now()+interval '5 minutes'),
  constraint user_locations_expiry_after_capture check (expires_at>captured_at),
  constraint user_locations_enabled_requires_consent check (not is_enabled or consented_at is not null),
  constraint user_locations_source_check check (source in ('device_foreground','device_approximate'))
);
comment on table private.user_locations is 'Exact user coordinates. Server-only and absent from public generated types.';
create index user_locations_location_gist on private.user_locations using gist(location);
create index user_locations_enabled_expiry_idx on private.user_locations(expires_at,captured_at,user_id) where is_enabled;
create trigger user_locations_set_updated_at before update on private.user_locations for each row execute function private.set_updated_at();

create table private.location_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  source text,
  accuracy_meters integer,
  occurred_at timestamptz not null default now(),
  constraint location_events_type_check check (event_type in ('set','disable')),
  constraint location_events_accuracy_nonnegative check (accuracy_meters is null or accuracy_meters>=0)
);
comment on table private.location_events is 'Immutable location audit without coordinates.';
create index location_events_user_occurred_idx on private.location_events(user_id,occurred_at desc);

create table public.friendships (
  id uuid primary key default extensions.gen_random_uuid(),
  requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,
  pair_low_id uuid generated always as (least(requester_id,addressee_id)) stored,
  pair_high_id uuid generated always as (greatest(requester_id,addressee_id)) stored,
  status public.friendship_status not null default 'pending',
  greeting_message text,
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint friendships_not_self check (requester_id<>addressee_id),
  constraint friendships_greeting_length check (greeting_message is null or char_length(greeting_message)<=280),
  constraint friendships_response_timestamp check ((status='pending' and responded_at is null) or (status<>'pending' and responded_at is not null))
);
create unique index friendships_active_pair_unique_idx on public.friendships(pair_low_id,pair_high_id) where status in ('pending','accepted');
create index friendships_requester_status_created_idx on public.friendships(requester_id,status,created_at desc);
create index friendships_addressee_status_created_idx on public.friendships(addressee_id,status,created_at desc);
create index friendships_pair_history_idx on public.friendships(pair_low_id,pair_high_id,created_at desc);
create trigger friendships_set_updated_at before update on public.friendships for each row execute function private.set_updated_at();

create table public.user_blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  reason_code text,
  created_at timestamptz not null default now(),
  primary key(blocker_id,blocked_id),
  constraint user_blocks_not_self check (blocker_id<>blocked_id),
  constraint user_blocks_reason_length check (reason_code is null or char_length(reason_code)<=64)
);
create index user_blocks_blocked_idx on public.user_blocks(blocked_id,blocker_id);

create table public.reports (
  id uuid primary key default extensions.gen_random_uuid(),
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  target_user_id uuid references public.profiles(id) on delete set null,
  target_media_id uuid,
  target_message_id uuid,
  reason_code text not null,
  description text,
  evidence_json jsonb not null default '{}'::jsonb,
  status public.report_status not null default 'submitted',
  priority public.report_priority not null default 'normal',
  assigned_to uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  resolution_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reports_exactly_one_target check (num_nonnulls(target_user_id,target_media_id,target_message_id)=1),
  constraint reports_not_self_user check (target_user_id is null or target_user_id<>reporter_id),
  constraint reports_reason_format check (reason_code~'^[a-z][a-z0-9_]{1,63}$'),
  constraint reports_description_length check (description is null or char_length(description)<=2000),
  constraint reports_evidence_object check (jsonb_typeof(evidence_json)='object'),
  constraint reports_resolution_pair check ((status in ('resolved','dismissed') and resolved_at is not null) or (status not in ('resolved','dismissed') and resolved_at is null))
);
create index reports_reporter_created_idx on public.reports(reporter_id,created_at desc);
create index reports_status_priority_created_idx on public.reports(status,priority,created_at);
create index reports_target_user_idx on public.reports(target_user_id,created_at desc) where target_user_id is not null;
create index reports_target_message_idx on public.reports(target_message_id,created_at desc) where target_message_id is not null;
create index reports_assigned_to_idx on public.reports(assigned_to,status) where assigned_to is not null;
create trigger reports_set_updated_at before update on public.reports for each row execute function private.set_updated_at();

create table public.conversations (
  id uuid primary key default extensions.gen_random_uuid(),
  friendship_id uuid not null unique references public.friendships(id) on delete restrict,
  conversation_type public.conversation_type not null default 'direct',
  last_message_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index conversations_last_message_idx on public.conversations(last_message_at desc nulls last,id);
create trigger conversations_set_updated_at before update on public.conversations for each row execute function private.set_updated_at();

create table public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_read_message_id uuid,
  last_read_at timestamptz,
  is_muted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(conversation_id,user_id),
  constraint conversation_members_read_pair check ((last_read_message_id is null and last_read_at is null) or last_read_at is not null)
);
create index conversation_members_user_joined_idx on public.conversation_members(user_id,joined_at desc,conversation_id);
create trigger conversation_members_set_updated_at before update on public.conversation_members for each row execute function private.set_updated_at();

create table public.messages (
  id uuid primary key default extensions.gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  message_type public.message_type not null default 'text',
  body text,
  gift_transaction_id uuid,
  client_message_id uuid not null,
  moderation_status public.message_moderation_status not null default 'unreviewed',
  sent_at timestamptz not null default now(),
  edited_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint messages_text_shape check ((message_type='text' and body is not null and gift_transaction_id is null) or (message_type='gift' and gift_transaction_id is not null) or (message_type='system' and gift_transaction_id is null)),
  constraint messages_body_length check (body is null or char_length(body) between 1 and 2000),
  constraint messages_edit_after_send check (edited_at is null or edited_at>=sent_at),
  constraint messages_delete_after_send check (deleted_at is null or deleted_at>=sent_at),
  unique(sender_id,client_message_id)
);
create index messages_conversation_sent_idx on public.messages(conversation_id,sent_at desc,id desc);
create index messages_sender_sent_idx on public.messages(sender_id,sent_at desc);
create index messages_moderation_idx on public.messages(moderation_status,sent_at) where moderation_status in ('flagged','removed');
alter table public.conversation_members add constraint conversation_members_last_read_message_fkey foreign key(last_read_message_id) references public.messages(id) on delete set null;
alter table public.reports add constraint reports_target_message_id_fkey foreign key(target_message_id) references public.messages(id) on delete restrict;
create trigger messages_set_updated_at before update on public.messages for each row execute function private.set_updated_at();

create or replace function private.is_active_adult(p_user_id uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.profiles p join private.user_identity i on i.user_id=p.id where p.id=p_user_id and p.profile_status='active'::public.profile_status and p.deleted_at is null and i.account_status='active'::private.account_status and i.age_verified_at is not null and i.date_of_birth<=(current_date-interval '18 years')::date and i.terms_accepted_at is not null and i.community_rules_accepted_at is not null)
$$;
create or replace function private.users_are_blocked(p_user_a uuid,p_user_b uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.user_blocks b where (b.blocker_id=p_user_a and b.blocked_id=p_user_b) or (b.blocker_id=p_user_b and b.blocked_id=p_user_a))
$$;
create or replace function private.is_conversation_member(p_conversation_id uuid,p_user_id uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.conversation_members cm where cm.conversation_id=p_conversation_id and cm.user_id=p_user_id)
$$;
create or replace function private.distance_bucket(p_distance_meters double precision) returns text language sql immutable set search_path='' as $$
 select case when p_distance_meters<1000 then 'under_1km' when p_distance_meters<3000 then '1_to_3km' when p_distance_meters<5000 then '3_to_5km' when p_distance_meters<8000 then '5_to_8km' when p_distance_meters<15000 then '8_to_15km' else 'over_15km' end
$$;
revoke all on function private.is_active_adult(uuid) from public,anon,authenticated;
revoke all on function private.users_are_blocked(uuid,uuid) from public,anon,authenticated;
revoke all on function private.is_conversation_member(uuid,uuid) from public,anon,authenticated;
revoke all on function private.distance_bucket(double precision) from public,anon,authenticated;

create or replace function private.ensure_direct_conversation() returns trigger language plpgsql security definer set search_path='' as $$
declare v_conversation_id uuid;
begin
 if new.status='accepted'::public.friendship_status and old.status is distinct from new.status then
  insert into public.conversations(friendship_id) values(new.id) on conflict(friendship_id) do update set updated_at=now() returning id into v_conversation_id;
  insert into public.conversation_members(conversation_id,user_id) values(v_conversation_id,new.requester_id),(v_conversation_id,new.addressee_id) on conflict(conversation_id,user_id) do nothing;
 end if;
 return new;
end $$;
revoke all on function private.ensure_direct_conversation() from public,anon,authenticated;
create trigger friendships_create_direct_conversation after update of status on public.friendships for each row execute function private.ensure_direct_conversation();

create or replace function private.validate_message_insert() returns trigger language plpgsql security definer set search_path='' as $$
declare v_friendship public.friendships%rowtype; v_other_user uuid;
begin
 if not private.is_conversation_member(new.conversation_id,new.sender_id) then raise exception using errcode='42501',message='sender_not_conversation_member'; end if;
 select f.* into v_friendship from public.conversations c join public.friendships f on f.id=c.friendship_id where c.id=new.conversation_id;
 if not found or v_friendship.status<>'accepted'::public.friendship_status then raise exception using errcode='42501',message='accepted_friendship_required'; end if;
 v_other_user:=case when v_friendship.requester_id=new.sender_id then v_friendship.addressee_id else v_friendship.requester_id end;
 if private.users_are_blocked(new.sender_id,v_other_user) then raise exception using errcode='42501',message='messaging_blocked'; end if;
 return new;
end $$;
revoke all on function private.validate_message_insert() from public,anon,authenticated;
create trigger messages_validate_insert before insert on public.messages for each row execute function private.validate_message_insert();

create or replace function public.set_my_location(p_latitude double precision,p_longitude double precision,p_accuracy_meters integer,p_captured_at timestamptz,p_source text default 'device_foreground')
returns table(is_enabled boolean,captured_at timestamptz,expires_at timestamptz) language plpgsql security definer set search_path='' as $$
declare v_user_id uuid:=auth.uid(); v_now timestamptz:=now(); v_max_accuracy integer; v_stale_days integer; v_expires_at timestamptz;
begin
 if v_user_id is null then raise exception using errcode='42501',message='authentication_required'; end if;
 if not private.is_active_adult(v_user_id) then raise exception using errcode='42501',message='active_adult_account_required'; end if;
 if p_latitude is null or p_latitude < -90 or p_latitude > 90 or p_longitude is null or p_longitude < -180 or p_longitude > 180 then raise exception using errcode='22023',message='invalid_coordinates'; end if;
 if p_accuracy_meters is null or p_accuracy_meters<0 then raise exception using errcode='22023',message='invalid_location_accuracy'; end if;
 if p_captured_at is null or p_captured_at>v_now+interval '5 minutes' or p_captured_at<v_now-interval '24 hours' then raise exception using errcode='22023',message='invalid_location_capture_time'; end if;
 if p_source not in ('device_foreground','device_approximate') then raise exception using errcode='22023',message='invalid_location_source'; end if;
 select (value_json#>>'{}')::integer into v_max_accuracy from private.app_config where key='location_max_accuracy_meters';
 select (value_json#>>'{}')::integer into v_stale_days from private.app_config where key='location_stale_after_days';
 if p_accuracy_meters>coalesce(v_max_accuracy,5000) then raise exception using errcode='22023',message='location_accuracy_too_low'; end if;
 if exists(select 1 from private.location_events e where e.user_id=v_user_id and e.event_type='set' and e.occurred_at>v_now-interval '30 seconds') then raise exception using errcode='54000',message='location_update_rate_limited'; end if;
 v_expires_at:=p_captured_at+make_interval(days=>coalesce(v_stale_days,7));
 insert into private.user_locations(user_id,location,accuracy_meters,captured_at,consented_at,is_enabled,source,expires_at)
 values(v_user_id,extensions.st_setsrid(extensions.st_makepoint(p_longitude,p_latitude),4326)::extensions.geography,p_accuracy_meters,p_captured_at,v_now,true,p_source,v_expires_at)
 on conflict(user_id) do update set location=excluded.location,accuracy_meters=excluded.accuracy_meters,captured_at=excluded.captured_at,consented_at=excluded.consented_at,is_enabled=true,source=excluded.source,expires_at=excluded.expires_at;
 insert into private.location_events(user_id,event_type,source,accuracy_meters) values(v_user_id,'set',p_source,p_accuracy_meters);
 return query select true,p_captured_at,v_expires_at;
end $$;
revoke all on function public.set_my_location(double precision,double precision,integer,timestamptz,text) from public,anon;
grant execute on function public.set_my_location(double precision,double precision,integer,timestamptz,text) to authenticated;

create or replace function public.disable_my_location() returns boolean language plpgsql security definer set search_path='' as $$
declare v_user_id uuid:=auth.uid(); v_updated integer:=0;
begin
 if v_user_id is null then raise exception using errcode='42501',message='authentication_required'; end if;
 update private.user_locations set is_enabled=false,expires_at=least(expires_at,now()) where user_id=v_user_id;
 get diagnostics v_updated=row_count;
 insert into private.location_events(user_id,event_type) values(v_user_id,'disable');
 return v_updated>0;
end $$;
revoke all on function public.disable_my_location() from public,anon;
grant execute on function public.disable_my_location() to authenticated;

create or replace function public.find_nearby_profiles(p_radius_meters integer default 8000,p_limit integer default 20,p_cursor uuid default null)
returns table(id uuid,username text,display_name text,bio text,gender public.gender_identity,province_id bigint,avatar_media_id uuid,is_creator boolean,distance_bucket text)
language sql stable security definer set search_path='' as $$
 with caller as (
  select ul.location,
   least(greatest(coalesce(p_radius_meters,8000),1),coalesce((select (c.value_json#>>'{}')::integer from private.app_config c where c.key='location_max_radius_meters'),15000))::double precision radius_meters,
   least(greatest(coalesce(p_limit,20),1),50) result_limit,
   coalesce((select (c.value_json#>>'{}')::integer from private.app_config c where c.key='location_max_accuracy_meters'),5000) max_accuracy
  from private.user_locations ul join public.profiles cp on cp.id=ul.user_id
  where ul.user_id=auth.uid() and cp.discovery_enabled and cp.nearby_enabled and ul.is_enabled and ul.expires_at>now() and private.is_active_adult(ul.user_id)
 ), candidates as (
  select p.id,p.username::text username,p.display_name,p.bio,p.gender,p.province_id,p.avatar_media_id,p.is_creator,
   extensions.st_distance(ul.location,caller.location) distance_meters,caller.result_limit
  from caller join private.user_locations ul on ul.user_id<>auth.uid() and ul.is_enabled and ul.expires_at>now() and ul.accuracy_meters<=caller.max_accuracy and extensions.st_dwithin(ul.location,caller.location,caller.radius_meters)
  join public.profiles p on p.id=ul.user_id
  where p.profile_status='active'::public.profile_status and p.deleted_at is null and p.discovery_enabled and p.nearby_enabled and private.is_active_adult(p.id) and not private.users_are_blocked(auth.uid(),p.id)
 ), cursor_distance as (select c.distance_meters from candidates c where c.id=p_cursor)
 select c.id,c.username,c.display_name,c.bio,c.gender,c.province_id,c.avatar_media_id,c.is_creator,private.distance_bucket(c.distance_meters)
 from candidates c
 where p_cursor is null or (c.distance_meters,c.id)>((select distance_meters from cursor_distance),p_cursor)
 order by c.distance_meters,c.id
 limit (select result_limit from caller)
$$;
revoke all on function public.find_nearby_profiles(integer,integer,uuid) from public,anon;
grant execute on function public.find_nearby_profiles(integer,integer,uuid) to authenticated;

create or replace function public.find_province_profiles(p_province_id bigint,p_limit integer default 20,p_cursor uuid default null)
returns setof public.profiles language sql stable security definer set search_path='' as $$
 select p.* from public.profiles p where p.province_id=p_province_id and p.id<>auth.uid() and p.profile_status='active'::public.profile_status and p.deleted_at is null and p.discovery_enabled and private.is_active_adult(auth.uid()) and private.is_active_adult(p.id) and not private.users_are_blocked(auth.uid(),p.id) and (p_cursor is null or p.id>p_cursor) order by p.id limit least(greatest(coalesce(p_limit,20),1),50)
$$;
revoke all on function public.find_province_profiles(bigint,integer,uuid) from public,anon;
grant execute on function public.find_province_profiles(bigint,integer,uuid) to authenticated;

create or replace function public.send_friend_request(p_addressee_id uuid,p_greeting_message text default null) returns public.friendships language plpgsql security definer set search_path='' as $$
declare v_user_id uuid:=auth.uid(); v_result public.friendships;
begin
 if v_user_id is null then raise exception using errcode='42501',message='authentication_required'; end if;
 if p_addressee_id is null or p_addressee_id=v_user_id then raise exception using errcode='22023',message='invalid_friend_target'; end if;
 if not private.is_active_adult(v_user_id) or not private.is_active_adult(p_addressee_id) then raise exception using errcode='42501',message='active_adult_accounts_required'; end if;
 if private.users_are_blocked(v_user_id,p_addressee_id) then raise exception using errcode='42501',message='friendship_blocked'; end if;
 if p_greeting_message is not null and char_length(p_greeting_message)>280 then raise exception using errcode='22001',message='greeting_too_long'; end if;
 if exists(select 1 from public.friendships f where f.pair_low_id=least(v_user_id,p_addressee_id) and f.pair_high_id=greatest(v_user_id,p_addressee_id) and f.status in ('pending','accepted')) then raise exception using errcode='23505',message='active_friendship_exists'; end if;
 insert into public.friendships(requester_id,addressee_id,greeting_message) values(v_user_id,p_addressee_id,nullif(btrim(p_greeting_message),'')) returning * into v_result;
 return v_result;
end $$;
revoke all on function public.send_friend_request(uuid,text) from public,anon;
grant execute on function public.send_friend_request(uuid,text) to authenticated;

create or replace function public.respond_to_friend_request(p_friendship_id uuid,p_accept boolean) returns public.friendships language plpgsql security definer set search_path='' as $$
declare v_user_id uuid:=auth.uid(); v_result public.friendships;
begin
 if v_user_id is null then raise exception using errcode='42501',message='authentication_required'; end if;
 update public.friendships f set status=case when p_accept then 'accepted'::public.friendship_status else 'declined'::public.friendship_status end,responded_at=now()
 where f.id=p_friendship_id and f.addressee_id=v_user_id and f.status='pending'::public.friendship_status and not private.users_are_blocked(f.requester_id,f.addressee_id) returning * into v_result;
 if v_result.id is null then raise exception using errcode='42501',message='pending_request_not_available'; end if;
 return v_result;
end $$;
revoke all on function public.respond_to_friend_request(uuid,boolean) from public,anon;
grant execute on function public.respond_to_friend_request(uuid,boolean) to authenticated;

create or replace function public.cancel_friend_request(p_friendship_id uuid) returns boolean language plpgsql security definer set search_path='' as $$
declare v_user_id uuid:=auth.uid(); begin
 if v_user_id is null then raise exception using errcode='42501',message='authentication_required'; end if;
 update public.friendships set status='cancelled'::public.friendship_status,responded_at=now() where id=p_friendship_id and requester_id=v_user_id and status='pending'::public.friendship_status;
 return found;
end $$;
revoke all on function public.cancel_friend_request(uuid) from public,anon;
grant execute on function public.cancel_friend_request(uuid) to authenticated;

create or replace function public.block_user(p_blocked_id uuid,p_reason_code text default null) returns boolean language plpgsql security definer set search_path='' as $$
declare v_user_id uuid:=auth.uid(); begin
 if v_user_id is null then raise exception using errcode='42501',message='authentication_required'; end if;
 if p_blocked_id is null or p_blocked_id=v_user_id then raise exception using errcode='22023',message='invalid_block_target'; end if;
 if not exists(select 1 from public.profiles p where p.id=p_blocked_id) then raise exception using errcode='23503',message='block_target_not_found'; end if;
 insert into public.user_blocks(blocker_id,blocked_id,reason_code) values(v_user_id,p_blocked_id,nullif(btrim(p_reason_code),'')) on conflict(blocker_id,blocked_id) do update set reason_code=excluded.reason_code;
 update public.friendships f set status='cancelled'::public.friendship_status,responded_at=coalesce(f.responded_at,now()) where f.pair_low_id=least(v_user_id,p_blocked_id) and f.pair_high_id=greatest(v_user_id,p_blocked_id) and f.status in ('pending','accepted');
 return true;
end $$;
revoke all on function public.block_user(uuid,text) from public,anon;
grant execute on function public.block_user(uuid,text) to authenticated;

create or replace function public.unblock_user(p_blocked_id uuid) returns boolean language plpgsql security definer set search_path='' as $$
declare v_user_id uuid:=auth.uid(); begin
 if v_user_id is null then raise exception using errcode='42501',message='authentication_required'; end if;
 delete from public.user_blocks where blocker_id=v_user_id and blocked_id=p_blocked_id;
 return found;
end $$;
revoke all on function public.unblock_user(uuid) from public,anon;
grant execute on function public.unblock_user(uuid) to authenticated;

create or replace function public.create_report(p_target_user_id uuid default null,p_target_media_id uuid default null,p_target_message_id uuid default null,p_reason_code text default 'other',p_description text default null,p_evidence_json jsonb default '{}'::jsonb) returns uuid language plpgsql security definer set search_path='' as $$
declare v_user_id uuid:=auth.uid(); v_id uuid;
begin
 if v_user_id is null then raise exception using errcode='42501',message='authentication_required'; end if;
 if not private.is_active_adult(v_user_id) then raise exception using errcode='42501',message='active_adult_account_required'; end if;
 if num_nonnulls(p_target_user_id,p_target_media_id,p_target_message_id)<>1 then raise exception using errcode='22023',message='exactly_one_report_target_required'; end if;
 if p_target_user_id=v_user_id then raise exception using errcode='22023',message='cannot_report_self'; end if;
 if p_target_message_id is not null and not exists(select 1 from public.messages m where m.id=p_target_message_id and private.is_conversation_member(m.conversation_id,v_user_id)) then raise exception using errcode='42501',message='message_not_reportable'; end if;
 insert into public.reports(reporter_id,target_user_id,target_media_id,target_message_id,reason_code,description,evidence_json) values(v_user_id,p_target_user_id,p_target_media_id,p_target_message_id,btrim(p_reason_code),nullif(btrim(p_description),''),coalesce(p_evidence_json,'{}'::jsonb)) returning id into v_id;
 return v_id;
end $$;
revoke all on function public.create_report(uuid,uuid,uuid,text,text,jsonb) from public,anon;
grant execute on function public.create_report(uuid,uuid,uuid,text,text,jsonb) to authenticated;

create or replace function public.get_my_reports(p_limit integer default 20,p_cursor uuid default null)
returns table(id uuid,target_type text,reason_code text,status public.report_status,created_at timestamptz,resolved_at timestamptz) language sql stable security definer set search_path='' as $$
 select r.id,case when r.target_user_id is not null then 'user' when r.target_message_id is not null then 'message' else 'media' end,r.reason_code,r.status,r.created_at,r.resolved_at from public.reports r where r.reporter_id=auth.uid() and (p_cursor is null or r.id>p_cursor) order by r.id limit least(greatest(coalesce(p_limit,20),1),50)
$$;
revoke all on function public.get_my_reports(integer,uuid) from public,anon;
grant execute on function public.get_my_reports(integer,uuid) to authenticated;

create or replace function public.send_message(p_conversation_id uuid,p_body text,p_client_message_id uuid) returns public.messages language plpgsql security definer set search_path='' as $$
declare v_user_id uuid:=auth.uid(); v_result public.messages;
begin
 if v_user_id is null then raise exception using errcode='42501',message='authentication_required'; end if;
 if not private.is_active_adult(v_user_id) then raise exception using errcode='42501',message='active_adult_account_required'; end if;
 if p_client_message_id is null then raise exception using errcode='22023',message='client_message_id_required'; end if;
 if nullif(btrim(p_body),'') is null or char_length(p_body)>2000 then raise exception using errcode='22023',message='invalid_message_body'; end if;
 insert into public.messages(conversation_id,sender_id,message_type,body,client_message_id) values(p_conversation_id,v_user_id,'text'::public.message_type,btrim(p_body),p_client_message_id)
 on conflict(sender_id,client_message_id) do update set sender_id=excluded.sender_id returning * into v_result;
 update public.conversations set last_message_at=v_result.sent_at where id=p_conversation_id;
 return v_result;
end $$;
revoke all on function public.send_message(uuid,text,uuid) from public,anon;
grant execute on function public.send_message(uuid,text,uuid) to authenticated;

create or replace function public.mark_conversation_read(p_conversation_id uuid,p_message_id uuid default null) returns boolean language plpgsql security definer set search_path='' as $$
declare v_user_id uuid:=auth.uid(); begin
 if v_user_id is null then raise exception using errcode='42501',message='authentication_required'; end if;
 if p_message_id is not null and not exists(select 1 from public.messages m where m.id=p_message_id and m.conversation_id=p_conversation_id) then raise exception using errcode='23503',message='message_not_in_conversation'; end if;
 update public.conversation_members set last_read_message_id=p_message_id,last_read_at=now() where conversation_id=p_conversation_id and user_id=v_user_id;
 return found;
end $$;
revoke all on function public.mark_conversation_read(uuid,uuid) from public,anon;
grant execute on function public.mark_conversation_read(uuid,uuid) to authenticated;

alter table private.user_locations enable row level security;
alter table private.location_events enable row level security;
alter table public.friendships enable row level security;
alter table public.user_blocks enable row level security;
alter table public.reports enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;
revoke all on private.user_locations from public,anon,authenticated;
revoke all on private.location_events from public,anon,authenticated;
revoke all on public.friendships from public,anon,authenticated;
revoke all on public.user_blocks from public,anon,authenticated;
revoke all on public.reports from public,anon,authenticated;
revoke all on public.conversations from public,anon,authenticated;
revoke all on public.conversation_members from public,anon,authenticated;
revoke all on public.messages from public,anon,authenticated;
grant select on public.friendships,public.user_blocks,public.conversations,public.conversation_members,public.messages to authenticated;
create policy friendships_select_participants on public.friendships for select to authenticated using ((select auth.uid()) in (requester_id,addressee_id));
create policy user_blocks_select_own on public.user_blocks for select to authenticated using ((select auth.uid())=blocker_id);
create policy reports_select_own on public.reports for select to authenticated using ((select auth.uid())=reporter_id);
create policy conversations_select_members on public.conversations for select to authenticated using (private.is_conversation_member(id,(select auth.uid())));
create policy conversation_members_select_members on public.conversation_members for select to authenticated using (private.is_conversation_member(conversation_id,(select auth.uid())));
create policy messages_select_members on public.messages for select to authenticated using (private.is_conversation_member(conversation_id,(select auth.uid())));

do $$ begin
 if exists(select 1 from pg_publication where pubname='supabase_realtime') then
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='friendships') then alter publication supabase_realtime add table public.friendships; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='conversation_members') then alter publication supabase_realtime add table public.conversation_members; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='messages') then alter publication supabase_realtime add table public.messages; end if;
 end if;
end $$;

comment on function public.set_my_location(double precision,double precision,integer,timestamptz,text) is 'Stores only the authenticated user location and returns no coordinates.';
comment on function public.find_nearby_profiles(integer,integer,uuid) is 'Uses PostGIS and returns distance buckets only.';
comment on table public.friendships is 'One active normalized friendship per pair; chat opens only after acceptance.';
comment on table public.messages is 'Direct messages inserted through protected RPC after accepted friendship.';
